// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tasks.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (id, created_at, updated_at, user_id, title, end_date, description, priority, tag, state, parent_id)
VALUES (
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING id, created_at, updated_at, user_id, title, end_date, description, priority, tag, state, parent_id
`

type CreateTaskParams struct {
	UserID      uuid.UUID
	Title       string
	EndDate     time.Time
	Description string
	Priority    string
	Tag         string
	State       string
	ParentID    uuid.NullUUID
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, createTask,
		arg.UserID,
		arg.Title,
		arg.EndDate,
		arg.Description,
		arg.Priority,
		arg.Tag,
		arg.State,
		arg.ParentID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.Title,
		&i.EndDate,
		&i.Description,
		&i.Priority,
		&i.Tag,
		&i.State,
		&i.ParentID,
	)
	return i, err
}

const createTaskEditors = `-- name: CreateTaskEditors :one
INSERT INTO task_editors (task_id, editor_id)
VALUES ($1, $2)
RETURNING task_id, editor_id
`

type CreateTaskEditorsParams struct {
	TaskID   uuid.UUID
	EditorID uuid.UUID
}

func (q *Queries) CreateTaskEditors(ctx context.Context, arg CreateTaskEditorsParams) (TaskEditor, error) {
	row := q.db.QueryRowContext(ctx, createTaskEditors, arg.TaskID, arg.EditorID)
	var i TaskEditor
	err := row.Scan(&i.TaskID, &i.EditorID)
	return i, err
}

const getTaskByID = `-- name: GetTaskByID :one
SELECT id, created_at, updated_at, user_id, title, end_date, description, priority, tag, state, parent_id FROM tasks WHERE id = $1
`

func (q *Queries) GetTaskByID(ctx context.Context, id uuid.UUID) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTaskByID, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.Title,
		&i.EndDate,
		&i.Description,
		&i.Priority,
		&i.Tag,
		&i.State,
		&i.ParentID,
	)
	return i, err
}

const getTaskEditorsByTaskID = `-- name: GetTaskEditorsByTaskID :many
SELECT editor_id FROM task_editors WHERE task_id = $1
`

func (q *Queries) GetTaskEditorsByTaskID(ctx context.Context, taskID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, getTaskEditorsByTaskID, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var editor_id uuid.UUID
		if err := rows.Scan(&editor_id); err != nil {
			return nil, err
		}
		items = append(items, editor_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
