// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tasks.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (id, created_at, updated_at, user_id, title, end_date, description, priority, tag, state, parent_id, task_editors)
VALUES (
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
) 
RETURNING id, created_at, updated_at, user_id, title, end_date, description, priority, tag, state, parent_id, task_editors
`

type CreateTaskParams struct {
	UserID      pgtype.UUID
	Title       string
	EndDate     pgtype.Timestamp
	Description string
	Priority    string
	Tag         string
	State       string
	ParentID    pgtype.UUID
	TaskEditors []pgtype.UUID
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.UserID,
		arg.Title,
		arg.EndDate,
		arg.Description,
		arg.Priority,
		arg.Tag,
		arg.State,
		arg.ParentID,
		arg.TaskEditors,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.Title,
		&i.EndDate,
		&i.Description,
		&i.Priority,
		&i.Tag,
		&i.State,
		&i.ParentID,
		&i.TaskEditors,
	)
	return i, err
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM tasks WHERE id = $1
`

func (q *Queries) DeleteTask(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTask, id)
	return err
}

const getCollaborativeTasksByParentID = `-- name: GetCollaborativeTasksByParentID :many
SELECT u.email, u.username, t.id, t.created_at, t.updated_at, t.user_id, t.title, t.end_date, t.description, t.priority, t.tag, t.state, t.parent_id, t.task_editors
FROM tasks t
JOIN users u ON t.user_id = u.id
WHERE t.parent_id = $1 OR t.id = $1
ORDER BY t.created_at ASC
`

type GetCollaborativeTasksByParentIDRow struct {
	Email       string
	Username    string
	ID          pgtype.UUID
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
	UserID      pgtype.UUID
	Title       string
	EndDate     pgtype.Timestamp
	Description string
	Priority    string
	Tag         string
	State       string
	ParentID    pgtype.UUID
	TaskEditors []pgtype.UUID
}

func (q *Queries) GetCollaborativeTasksByParentID(ctx context.Context, parentID pgtype.UUID) ([]GetCollaborativeTasksByParentIDRow, error) {
	rows, err := q.db.Query(ctx, getCollaborativeTasksByParentID, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCollaborativeTasksByParentIDRow
	for rows.Next() {
		var i GetCollaborativeTasksByParentIDRow
		if err := rows.Scan(
			&i.Email,
			&i.Username,
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.Title,
			&i.EndDate,
			&i.Description,
			&i.Priority,
			&i.Tag,
			&i.State,
			&i.ParentID,
			&i.TaskEditors,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getParentTasks = `-- name: GetParentTasks :many
SELECT u.email, u.username, t.id, t.created_at, t.updated_at, t.user_id, t.title, t.end_date, t.description, t.priority, t.tag, t.state, t.parent_id, t.task_editors
FROM tasks t
JOIN users u ON t.user_id = u.id
WHERE t.parent_id IS NULL AND t.tag = 'collaborative'
ORDER BY t.created_at ASC
`

type GetParentTasksRow struct {
	Email       string
	Username    string
	ID          pgtype.UUID
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
	UserID      pgtype.UUID
	Title       string
	EndDate     pgtype.Timestamp
	Description string
	Priority    string
	Tag         string
	State       string
	ParentID    pgtype.UUID
	TaskEditors []pgtype.UUID
}

func (q *Queries) GetParentTasks(ctx context.Context) ([]GetParentTasksRow, error) {
	rows, err := q.db.Query(ctx, getParentTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetParentTasksRow
	for rows.Next() {
		var i GetParentTasksRow
		if err := rows.Scan(
			&i.Email,
			&i.Username,
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.Title,
			&i.EndDate,
			&i.Description,
			&i.Priority,
			&i.Tag,
			&i.State,
			&i.ParentID,
			&i.TaskEditors,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPublicTasks = `-- name: GetPublicTasks :many
SELECT t.id, t.created_at, t.updated_at, t.user_id, t.title, t.end_date, t.description, t.priority, t.tag, t.state, t.parent_id, t.task_editors, u.email, u.username
FROM tasks t
JOIN users u ON t.user_id = u.id
WHERE t.tag = 'public'
ORDER BY t.created_at ASC
`

type GetPublicTasksRow struct {
	ID          pgtype.UUID
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
	UserID      pgtype.UUID
	Title       string
	EndDate     pgtype.Timestamp
	Description string
	Priority    string
	Tag         string
	State       string
	ParentID    pgtype.UUID
	TaskEditors []pgtype.UUID
	Email       string
	Username    string
}

func (q *Queries) GetPublicTasks(ctx context.Context) ([]GetPublicTasksRow, error) {
	rows, err := q.db.Query(ctx, getPublicTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPublicTasksRow
	for rows.Next() {
		var i GetPublicTasksRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.Title,
			&i.EndDate,
			&i.Description,
			&i.Priority,
			&i.Tag,
			&i.State,
			&i.ParentID,
			&i.TaskEditors,
			&i.Email,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTaskByID = `-- name: GetTaskByID :one
SELECT id, created_at, updated_at, user_id, title, end_date, description, priority, tag, state, parent_id, task_editors FROM tasks WHERE id = $1
`

func (q *Queries) GetTaskByID(ctx context.Context, id pgtype.UUID) (Task, error) {
	row := q.db.QueryRow(ctx, getTaskByID, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.Title,
		&i.EndDate,
		&i.Description,
		&i.Priority,
		&i.Tag,
		&i.State,
		&i.ParentID,
		&i.TaskEditors,
	)
	return i, err
}

const getTasksByUserID = `-- name: GetTasksByUserID :many
SELECT id, created_at, updated_at, user_id, title, end_date, description, priority, tag, state, parent_id, task_editors FROM tasks WHERE user_id = $1 ORDER BY created_at ASC
`

func (q *Queries) GetTasksByUserID(ctx context.Context, userID pgtype.UUID) ([]Task, error) {
	rows, err := q.db.Query(ctx, getTasksByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.Title,
			&i.EndDate,
			&i.Description,
			&i.Priority,
			&i.Tag,
			&i.State,
			&i.ParentID,
			&i.TaskEditors,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks
SET title = $2,
    end_date = $3,
    description = $4,
    priority = $5,
    state = $6,
    tag = $7,
    task_editors = $8,
    parent_id = $9,
    updated_at = NOW()
WHERE id = $1
RETURNING id, created_at, updated_at, user_id, title, end_date, description, priority, tag, state, parent_id, task_editors
`

type UpdateTaskParams struct {
	ID          pgtype.UUID
	Title       string
	EndDate     pgtype.Timestamp
	Description string
	Priority    string
	State       string
	Tag         string
	TaskEditors []pgtype.UUID
	ParentID    pgtype.UUID
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTask,
		arg.ID,
		arg.Title,
		arg.EndDate,
		arg.Description,
		arg.Priority,
		arg.State,
		arg.Tag,
		arg.TaskEditors,
		arg.ParentID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.Title,
		&i.EndDate,
		&i.Description,
		&i.Priority,
		&i.Tag,
		&i.State,
		&i.ParentID,
		&i.TaskEditors,
	)
	return i, err
}
