// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tasks.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (id, created_at, updated_at, user_id, title, end_date, description, priority, tag, state, parent_id)
VALUES (
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING id, created_at, updated_at, user_id, title, end_date, description, priority, tag, state, parent_id
`

type CreateTaskParams struct {
	UserID      uuid.UUID
	Title       string
	EndDate     time.Time
	Description string
	Priority    string
	Tag         string
	State       string
	ParentID    uuid.NullUUID
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, createTask,
		arg.UserID,
		arg.Title,
		arg.EndDate,
		arg.Description,
		arg.Priority,
		arg.Tag,
		arg.State,
		arg.ParentID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.Title,
		&i.EndDate,
		&i.Description,
		&i.Priority,
		&i.Tag,
		&i.State,
		&i.ParentID,
	)
	return i, err
}

const createTaskEditors = `-- name: CreateTaskEditors :one
INSERT INTO task_editors (task_id, editor_id)
VALUES ($1, $2)
RETURNING task_id, editor_id
`

type CreateTaskEditorsParams struct {
	TaskID   uuid.UUID
	EditorID uuid.UUID
}

func (q *Queries) CreateTaskEditors(ctx context.Context, arg CreateTaskEditorsParams) (TaskEditor, error) {
	row := q.db.QueryRowContext(ctx, createTaskEditors, arg.TaskID, arg.EditorID)
	var i TaskEditor
	err := row.Scan(&i.TaskID, &i.EditorID)
	return i, err
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM tasks WHERE id = $1
`

func (q *Queries) DeleteTask(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteTask, id)
	return err
}

const getCollaborativeTasksByParentID = `-- name: GetCollaborativeTasksByParentID :many
SELECT u.email, u.username, t.id, t.created_at, t.updated_at, t.user_id, t.title, t.end_date, t.description, t.priority, t.tag, t.state, t.parent_id
FROM tasks t
JOIN users u ON t.user_id = u.id
WHERE t.parent_id = $1 OR t.id = $1
ORDER BY t.created_at ASC
`

type GetCollaborativeTasksByParentIDRow struct {
	Email       string
	Username    string
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	UserID      uuid.UUID
	Title       string
	EndDate     time.Time
	Description string
	Priority    string
	Tag         string
	State       string
	ParentID    uuid.NullUUID
}

func (q *Queries) GetCollaborativeTasksByParentID(ctx context.Context, parentID uuid.NullUUID) ([]GetCollaborativeTasksByParentIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getCollaborativeTasksByParentID, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCollaborativeTasksByParentIDRow
	for rows.Next() {
		var i GetCollaborativeTasksByParentIDRow
		if err := rows.Scan(
			&i.Email,
			&i.Username,
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.Title,
			&i.EndDate,
			&i.Description,
			&i.Priority,
			&i.Tag,
			&i.State,
			&i.ParentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTaskByID = `-- name: GetTaskByID :one
SELECT id, created_at, updated_at, user_id, title, end_date, description, priority, tag, state, parent_id FROM tasks WHERE id = $1
`

func (q *Queries) GetTaskByID(ctx context.Context, id uuid.UUID) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTaskByID, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.Title,
		&i.EndDate,
		&i.Description,
		&i.Priority,
		&i.Tag,
		&i.State,
		&i.ParentID,
	)
	return i, err
}

const getTaskEditorsByTaskID = `-- name: GetTaskEditorsByTaskID :many
SELECT editor_id FROM task_editors WHERE task_id = $1
`

func (q *Queries) GetTaskEditorsByTaskID(ctx context.Context, taskID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, getTaskEditorsByTaskID, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var editor_id uuid.UUID
		if err := rows.Scan(&editor_id); err != nil {
			return nil, err
		}
		items = append(items, editor_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTasksByUserID = `-- name: GetTasksByUserID :many
SELECT id, created_at, updated_at, user_id, title, end_date, description, priority, tag, state, parent_id FROM tasks WHERE user_id = $1 ORDER BY created_at ASC
`

func (q *Queries) GetTasksByUserID(ctx context.Context, userID uuid.UUID) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, getTasksByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.Title,
			&i.EndDate,
			&i.Description,
			&i.Priority,
			&i.Tag,
			&i.State,
			&i.ParentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks
SET title = $2,
    end_date = $3,
    description = $4,
    priority = $5,
    state = $6,
    updated_at = NOW()
WHERE id = $1
RETURNING id, created_at, updated_at, user_id, title, end_date, description, priority, tag, state, parent_id
`

type UpdateTaskParams struct {
	ID          uuid.UUID
	Title       string
	EndDate     time.Time
	Description string
	Priority    string
	State       string
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, updateTask,
		arg.ID,
		arg.Title,
		arg.EndDate,
		arg.Description,
		arg.Priority,
		arg.State,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.Title,
		&i.EndDate,
		&i.Description,
		&i.Priority,
		&i.Tag,
		&i.State,
		&i.ParentID,
	)
	return i, err
}
